language: node_js
sudo: false
node_js:
  - 0.12
  - 4
  - 5

cache:
   directories:
     - node_modules

before_script:
  - npm install -g gulp

after_success:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < ./coverage/mocha/lcov.info

deploy:
  provider: npm
  api_key: $NPM_API_KEY
  email: thaiat@ipelia.com
  on:
    tags: true
    all_branches: true
    repo: mcfly-io/gulp-mux
    node: '0.12' # this should be quoted; otherwise, 0.10 would not work
